
    create table tbl_pedido (
       pedido_id int8 generated by default as identity,
        pedido_endereco varchar(255),
        pedido_moment timestamp,
        pedido_status varchar(255),
        primary key (pedido_id)
    );

    create table tbl_pedido_produto (
       pedido_id int8 not null,
        produto_id int8 not null
    );

    create table tbl_produto (
       produto_id int8 generated by default as identity,
        produto_descricao varchar(255),
        produto_nome varchar(255),
        produto_preco float8,
        primary key (produto_id)
    );

    alter table if exists tbl_pedido_produto 
       add constraint FKpjufirng8dng4teadgqwd9p67 
       foreign key (produto_id) 
       references tbl_produto;

    alter table if exists tbl_pedido_produto 
       add constraint FKm2088c5om3jd2d6t1mk100u4b 
       foreign key (pedido_id) 
       references tbl_pedido;
